version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./app:/app/app
      - ./faiss_index:/app/faiss_index
      - ./pip_cache:/root/.cache/pip
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    networks:
      - agex-network
    depends_on:
      feed-educator:
        condition: service_completed_successfully
      redis:
        condition: service_started

  feed-educator:
    build: .
    volumes:
      - ./app:/app/app
      - ./faiss_index:/app/faiss_index
      - ./pip_cache:/root/.cache/pip
    command: python app/agents/educator/feed.py
    env_file:
      - .env
    networks:
      - agex-network

  feed-auditor:
    build: .
    volumes:
      - ./app:/app/app
      - ./faiss_index:/app/faiss_index
      - ./pip_cache:/root/.cache/pip
    command: python app/agents/auditor/feed.py
    env_file:
      - .env
    networks:
      - agex-network

  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data
    networks:
      - agex-network

networks:
  agex-network:
    driver: bridge

volumes:
  pip_cache:
  redis_data:
