### Create a new chat session
POST http://localhost:8000/api/create
Content-Type: application/json


### List chat sessions
GET http://localhost:8000/api/list
Content-Type: application/json

### History chat sessions
GET http://localhost:8000/history/48957693748
Content-Type: application/json


###
POST http://localhost:8000/api/query
Content-Type: application/json

{
    "query": "What is the role of a blockchain node?"
}

###
POST http://localhost:8000/api/query
Content-Type: application/json

{
    "query": "What is the security audit of the contract 0x45343543543432432342647654?"
}

###
POST http://localhost:8000/api/query
Content-Type: application/json

{
    "query": "Has 0x45343543543432432342647654 ever transacted with an exchange?"
}


### Sonic Network State
GET http://localhost:8000/api/network/state
Content-Type: application/json